"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import {
  generateSpeech,
  TranslationDisplayResult,
  TTS_VOICES,
  TtsVoice,
} from "@/lib/api";
import VoiceSelector from "./VoiceSelector";
import {
  AudioLines,
  Copy,
  CheckCheck,
  BookOpen,
  Mic,
  MessageSquare,
  Loader2,
  Volume2,
} from "lucide-react";

interface Props {
  result: TranslationDisplayResult;
  preferredVoice?: TtsVoice;
  autoGenerateVoiceover?: boolean;
  audioButtonLabel?: string;
  audioCaption?: string;
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback for older browsers
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [text]);

  return (
    <button
      onClick={handleCopy}
      title="Copy to clipboard"
      className="rounded-lg p-1.5 text-slate-400 transition hover:bg-indigo-50 hover:text-indigo-600 dark:text-slate-500 dark:hover:bg-slate-800 dark:hover:text-cyan-300"
    >
      {copied ? (
        <CheckCheck className="w-4 h-4 text-green-500" />
      ) : (
        <Copy className="w-4 h-4" />
      )}
    </button>
  );
}

interface ResultRowProps {
  icon: React.ReactNode;
  label: string;
  value: string;
  mono?: boolean;
}

function ResultRow({ icon, label, value, mono }: ResultRowProps) {
  return (
    <div className="space-y-1 rounded-xl border border-slate-100 bg-slate-50 px-4 py-3 dark:border-slate-800 dark:bg-slate-950">
      <div className="flex items-center justify-between">
        <span className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
          {icon}
          {label}
        </span>
        <CopyButton text={value} />
      </div>
      <p
        className={`text-base leading-relaxed text-slate-800 dark:text-slate-100 ${
          mono ? "font-mono text-sm" : ""
        }`}
      >
        {value}
      </p>
    </div>
  );
}

export default function TranslationResult({
  result,
  preferredVoice,
  autoGenerateVoiceover = false,
  audioButtonLabel = "Play Pronunciation",
  audioCaption = "Audio is generated only when you click play. The voice you hear is AI-generated.",
}: Props) {
  const [voice, setVoice] = useState<TtsVoice>(preferredVoice ?? "coral");
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [audioError, setAudioError] = useState<string | null>(null);
  const [audioLoading, setAudioLoading] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const audioCacheRef = useRef<Map<string, string>>(new Map());
  const autoGeneratedKeyRef = useRef<string | null>(null);

  const playAudioFromUrl = useCallback(async (url: string) => {
    if (!audioRef.current) {
      return;
    }

    audioRef.current.pause();
    audioRef.current.src = url;
    audioRef.current.load();

    try {
      await audioRef.current.play();
    } catch {
      // If autoplay is blocked, the audio controls remain available to the user.
    }
  }, []);

  const generateAndPlayAudio = useCallback(async (selectedVoice: TtsVoice) => {
    const cacheKey = `${result.target_language}:${selectedVoice}:${result.translation}`;
    const cachedUrl = audioCacheRef.current.get(cacheKey);

    setAudioError(null);

    if (cachedUrl) {
      setAudioUrl(cachedUrl);
      await playAudioFromUrl(cachedUrl);
      return;
    }

    setAudioLoading(true);

    try {
      const audioBlob = await generateSpeech({
        text: result.translation,
        language: result.target_language,
        voice: selectedVoice,
      });
      const nextAudioUrl = URL.createObjectURL(audioBlob);
      audioCacheRef.current.set(cacheKey, nextAudioUrl);
      setAudioUrl(nextAudioUrl);
      await playAudioFromUrl(nextAudioUrl);
    } catch (error) {
      setAudioError(
        error instanceof Error
          ? error.message
          : "Could not generate pronunciation audio."
      );
    } finally {
      setAudioLoading(false);
    }
  }, [playAudioFromUrl, result.target_language, result.translation]);

  const handlePlayPronunciation = useCallback(async () => {
    await generateAndPlayAudio(voice);
  }, [generateAndPlayAudio, voice]);

  useEffect(() => {
    if (preferredVoice) {
      setVoice(preferredVoice);
    }
  }, [preferredVoice, result.target_language, result.translation]);

  useEffect(() => {
    setAudioUrl(null);
    setAudioError(null);
    autoGeneratedKeyRef.current = null;
  }, [result.target_language, result.translation]);

  useEffect(() => {
    if (!autoGenerateVoiceover) {
      return;
    }

    const selectedVoice = preferredVoice ?? voice;
    const autoKey = `${result.target_language}:${selectedVoice}:${result.translation}`;
    if (autoGeneratedKeyRef.current === autoKey) {
      return;
    }

    autoGeneratedKeyRef.current = autoKey;
    void generateAndPlayAudio(selectedVoice);
  }, [
    autoGenerateVoiceover,
    generateAndPlayAudio,
    preferredVoice,
    result.target_language,
    result.translation,
    voice,
  ]);

  useEffect(() => {
    return () => {
      audioCacheRef.current.forEach((url) => URL.revokeObjectURL(url));
      audioCacheRef.current.clear();
    };
  }, []);

  return (
    <div className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-lg shadow-slate-200/70 transition-colors dark:border-slate-800 dark:bg-slate-900/90 dark:shadow-slate-950/40">
      {/* Header */}
      <div className="border-b border-slate-100 bg-gradient-to-r from-emerald-50 to-teal-50 px-6 py-4 dark:border-slate-800 dark:from-slate-900 dark:via-slate-900 dark:to-slate-800">
        <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-300">
          {result.source_language} → {result.target_language}
        </p>
      </div>

      <div className="p-6 space-y-3">
        <div className="space-y-3 rounded-xl border border-slate-200 bg-slate-50/80 px-4 py-4 dark:border-slate-700 dark:bg-slate-950/80">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <VoiceSelector
              value={voice}
              voices={[...TTS_VOICES]}
              onChange={(nextVoice) => setVoice(nextVoice as TtsVoice)}
              disabled={audioLoading}
            />
            <button
              type="button"
              onClick={handlePlayPronunciation}
              disabled={audioLoading}
              className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-teal-700 disabled:cursor-not-allowed disabled:bg-teal-300 dark:bg-cyan-500 dark:text-slate-950 dark:hover:bg-cyan-400 dark:disabled:bg-cyan-800"
            >
              {audioLoading ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Generating Audio...
                </>
              ) : (
                <>
                  <Volume2 className="h-4 w-4" />
                  {audioButtonLabel}
                </>
              )}
            </button>
          </div>

          <p className="text-xs leading-relaxed text-slate-500 dark:text-slate-400">
            {audioCaption}
          </p>

          {audioError && (
            <div className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700 dark:border-red-900/70 dark:bg-red-950/40 dark:text-red-200">
              {audioError}
            </div>
          )}

          <audio
            ref={audioRef}
            controls
            src={audioUrl ?? undefined}
            preload="none"
            className={`w-full ${audioUrl ? "block" : "hidden"}`}
          />
        </div>

        {result.transcript && (
          <ResultRow
            icon={<AudioLines className="w-3.5 h-3.5" />}
            label="Transcript"
            value={result.transcript}
          />
        )}

        {/* Translation */}
        <ResultRow
          icon={<MessageSquare className="w-3.5 h-3.5" />}
          label="Translation"
          value={result.translation}
        />

        {/* IPA */}
        <ResultRow
          icon={<BookOpen className="w-3.5 h-3.5" />}
          label="IPA Transcription"
          value={result.ipa}
          mono
        />

        {/* Simple Pronunciation */}
        <ResultRow
          icon={<Mic className="w-3.5 h-3.5" />}
          label="Pronunciation Guide"
          value={result.simple_pronunciation}
        />

        {/* Notes */}
        <div className="space-y-1 rounded-xl border border-amber-100 bg-amber-50 px-4 py-3 dark:border-amber-900/60 dark:bg-amber-950/35">
          <span className="text-xs font-semibold uppercase tracking-wide text-amber-700 dark:text-amber-300">
            Grammar &amp; Usage Notes
          </span>
          <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-200">{result.notes}</p>
        </div>
      </div>
    </div>
  );
}
